# Generated by Django 6.0 on 2026-01-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesmodel',
            name='tags',
        ),
        migrations.AddField(
            model_name='notesmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='notes.tagmodel'),
        ),
    ]
