# Generated by Django 6.0 on 2026-01-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notesmodel_tags_notesmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='pf',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
