# Generated by Django 6.0.1 on 2026-02-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notesmodel_pf_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesmodel',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
